name: Run Godog tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - uses: actions/setup-node@v2
      with:
        node-version: '12'

    - name: Install json-to-messages
      run: npm install -g @cucumber/json-to-messages

    - name: Install godog
      run: go get github.com/cucumber/godog/cmd/godog@v0.11.0

    - name: Run Godog tests
      id: tests
      env:
        CUCUMBER_PUBLISH_TOKEN: '${{ secrets.CUCUMBER_PUBLISH_TOKEN }}'
      run: |
        godog -f cucumber | json-to-messages > messages.json
        OUTPUT=$(curl -s -D - -H "Authorization: Bearer $CUCUMBER_PUBLISH_TOKEN" "https://messages.cucumber.io/api/reports")

        TARGET=$(echo $OUTPUT | grep -Eo 'https://cucumber-messages-app[^ ]+' | tr -d '\r')
        curl -v --upload-file messages.json "$TARGET"

        REPORT_LINK=$(echo $OUTPUT | grep -Eo 'https://reports.cucumber.io/reports/[0-9a-z-]+' | tr -d '\r')
        echo "::set-output name=REPORT_LINK::$REPORT_LINK"
    - uses: mshick/add-pr-comment@v1
      if: ${{ github.event_name == 'pull_request' }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        message: |
          View your Cucumber Reports there
          ${{ steps.tests.outputs.REPORT_LINK }}
        allow-repeats: true
